### ISSUE TITLE
Could not install under macOS

### ISSUE THREAD

**Issue by marcboeker** [tecbot/gorocksdb#105]
Hi,

I'm not able to get it installed under macOS 10.12.5 with RocksDB 5.4.6.

```
➜  CGO_CFLAGS="-I/usr/local/opt/rocksdb/include" CGO_LDFLAGS="-L/usr/local/opt/rocksdb/lib -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy -llz4" go get github.com/tecbot/gorocksdb
# github.com/tecbot/gorocksdb
could not determine kind of name for C.rocksdb_checkpoint_create
could not determine kind of name for C.rocksdb_checkpoint_object_destroy
could not determine kind of name for C.rocksdb_checkpoint_t
```

RocksDB is installed using Homebrew and located under /usr/local/opt/rocksdb wich points to the current version.

```
➜  ls -l /usr/local/opt/rocksdb
lrwxr-xr-x  1 marc  admin  23 Jun 22 19:12 /usr/local/opt/rocksdb -> ../Cellar/rocksdb/5.4.6
```

As you're requiring ```// #include "rocksdb/c.h"``` [here](https://github.com/tecbot/gorocksdb/blob/master/checkpoint.go#L4) I thought that the include path should be ```/usr/local/opt/rocksdb/include``` and not ```/usr/local/opt/rocksdb/include/rocksdb```? What am I doing wrong?

Thanks Marc

**Comment by yeaha** [comment]
I have the same issue.

os: 10.12.5
rocksdb: 5.4.6

**Comment by JelteF** [comment]
Can you try without the `/lib` suffix for the LDFLAGS? I think that should solve it.

**Comment by marcboeker** [comment]
I've already tried it before and now again. Using 

`CGO_CFLAGS="-I/usr/local/opt/rocksdb/include" CGO_LDFLAGS="-L/usr/local/opt/rocksdb -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy -llz4" go get github.com/tecbot/gorocksdb`

I still get 

```
# github.com/tecbot/gorocksdb
could not determine kind of name for C.rocksdb_checkpoint_create
could not determine kind of name for C.rocksdb_checkpoint_object_destroy
could not determine kind of name for C.rocksdb_checkpoint_t
```

**Comment by JelteF** [comment]
Ah I see the issue now. The checkpoint functions are only added in rocksdb 5.5, so either upgrade rocksdb to the latest release or downgrade to gorocksdb to before https://github.com/tecbot/gorocksdb/commit/1a1769a927137cecbf1d0af1c16744fd3adc1621

**Comment by JelteF** [comment]
I made a pull request to note the 5.5 dependency in the readme https://github.com/tecbot/gorocksdb/pull/106

**Comment by marcboeker** [comment]
Awesome, works like a charm now with 5.5.1. Thanks!
